#!/bin/sh

sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -solid "#111"

killall polybar
polybar -c ~/.config/polybar/config.ini main &

dunst &

wmname LG3D

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          1
bspc config window_gap           12
bspc config focused_border_color "#ff0000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a wine border=off
bspc rule -a Chromium desktop=^2
